-- AP-0014: tablas de identificacion del equipo origen en autenticacion.
-- Propiedad del nuevo sistema (no modifican dbo.users, de Drupal). Ejecutar en la base
-- sufiatulado como paso de despliegue (no hay cadena Alembic en el proyecto).

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SECURITY_DEVICE')
BEGIN
    CREATE TABLE dbo.SECURITY_DEVICE (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DEVICE_HASH NVARCHAR(128) NOT NULL,
        DEVICE_NAME NVARCHAR(200) NULL,
        USER_AGENT NVARCHAR(512) NULL,
        FIRST_SEEN DATETIME2 NOT NULL,
        LAST_SEEN DATETIME2 NOT NULL,
        STATUS NVARCHAR(20) NOT NULL DEFAULT 'activo',
        CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SECURITY_USER_DEVICE')
BEGIN
    CREATE TABLE dbo.SECURITY_USER_DEVICE (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USER_ID INT NOT NULL,
        DEVICE_HASH NVARCHAR(128) NOT NULL,
        DEVICE_NAME NVARCHAR(200) NOT NULL DEFAULT '',
        USER_AGENT NVARCHAR(512) NOT NULL DEFAULT '',
        FIRST_LOGIN NVARCHAR(40) NOT NULL DEFAULT '',
        LAST_LOGIN NVARCHAR(40) NOT NULL DEFAULT '',
        VECES_VISTO INT NOT NULL DEFAULT 1,
        TRUSTED BIT NOT NULL DEFAULT 0,
        CONSTRAINT UQ_USER_DEVICE UNIQUE (USER_ID, DEVICE_HASH)
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'SECURITY_AUTH_AUDIT')
BEGIN
    CREATE TABLE dbo.SECURITY_AUTH_AUDIT (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USER_ID INT NULL,
        DEVICE_HASH NVARCHAR(128) NULL,
        IP_ADDRESS NVARCHAR(100) NULL,
        LOGIN_DATE DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        AUTH_RESULT NVARCHAR(20) NULL
    );
END;
