from __future__ import annotations

from typing import Protocol

from src.domain.entities.banco_entity import BancoEntity


class BancoRepository(Protocol):
    """Puerto outbound para el catálogo dbo.bancos."""

    async def listar_paginado_async(
        self, page: int, page_size: int, nombre: str | None = None
    ) -> tuple[list[BancoEntity], int]: ...
    async def obtener_por_id_async(self, tid: int) -> BancoEntity | None: ...
    async def crear_async(self, entity: BancoEntity) -> BancoEntity: ...
    async def actualizar_async(self, tid: int, entity: BancoEntity) -> BancoEntity | None: ...
    async def eliminar_async(self, tid: int) -> bool: ...
    async def existe_referenciado_async(self, tid: int) -> bool: ...
