from __future__ import annotations

from typing import Protocol

from src.domain.entities.departamento_entity import DepartamentoEntity


class DepartamentoRepository(Protocol):
    """Puerto outbound para dbo.departamentos."""

    async def listar_paginado_async(
        self, page: int, page_size: int, nombre: str | None = None
    ) -> tuple[list[DepartamentoEntity], int]: ...
    async def obtener_por_id_async(self, did: int) -> DepartamentoEntity | None: ...
    async def crear_async(self, entity: DepartamentoEntity) -> DepartamentoEntity: ...
    async def actualizar_async(self, did: int, entity: DepartamentoEntity) -> DepartamentoEntity | None: ...
    async def eliminar_async(self, did: int) -> bool: ...
    async def existe_referenciado_async(self, did: int) -> bool: ...
