from __future__ import annotations

from typing import Protocol

from src.domain.entities.eps_entity import EpsEntity


class EpsRepository(Protocol):
    """Puerto outbound para el catálogo dbo.eps."""

    async def listar_paginado_async(
        self, page: int, page_size: int, nombre: str | None = None
    ) -> tuple[list[EpsEntity], int]: ...
    async def obtener_por_id_async(self, tid: int) -> EpsEntity | None: ...
    async def crear_async(self, entity: EpsEntity) -> EpsEntity: ...
    async def actualizar_async(self, tid: int, entity: EpsEntity) -> EpsEntity | None: ...
    async def eliminar_async(self, tid: int) -> bool: ...
    async def existe_referenciado_async(self, tid: int) -> bool: ...
