from __future__ import annotations

from datetime import datetime
from typing import Protocol

from src.domain.entities.comisionista_programa_entity import ComisionistaProgramaEntity
from src.domain.entities.comisionista_subprograma_entity import ComisionistaSubprogramaEntity
from src.domain.entities.perfil_contacto_entity import PerfilContactoEntity
from src.domain.entities.perfil_emocional_entity import PerfilEmocionalEntity
from src.domain.entities.perfil_tributario_entity import PerfilTributarioEntity


class PerfilRepository(Protocol):
    async def obtener_contacto_async(self, numero_documento: str) -> PerfilContactoEntity | None: ...
    async def guardar_contacto_async(self, entity: PerfilContactoEntity) -> PerfilContactoEntity: ...
    async def marcar_email_verificado_async(self, numero_documento: str, fecha: datetime) -> None: ...
    async def numero_documento_por_email_async(self, email: str) -> str | None: ...
    async def obtener_tributario_async(self, numero_documento: str) -> PerfilTributarioEntity | None: ...
    async def guardar_tributario_async(self, entity: PerfilTributarioEntity) -> PerfilTributarioEntity: ...
    async def obtener_emocional_async(self, numero_documento: str) -> PerfilEmocionalEntity | None: ...
    async def guardar_emocional_async(self, entity: PerfilEmocionalEntity) -> PerfilEmocionalEntity: ...
    async def listar_programas_async(self) -> list[ComisionistaProgramaEntity]: ...
    async def listar_subprogramas_async(self, cpid: int | None = None) -> list[ComisionistaSubprogramaEntity]: ...
