from __future__ import annotations

from typing import Protocol

from src.domain.entities.profesion_entity import ProfesionEntity


class ProfesionRepository(Protocol):
    """Puerto outbound para el catálogo dbo.taxonomia_profesion."""

    async def listar_paginado_async(
        self, page: int, page_size: int, nombre: str | None = None
    ) -> tuple[list[ProfesionEntity], int]: ...
    async def obtener_por_id_async(self, tid: int) -> ProfesionEntity | None: ...
    async def crear_async(self, entity: ProfesionEntity) -> ProfesionEntity: ...
    async def actualizar_async(self, tid: int, entity: ProfesionEntity) -> ProfesionEntity | None: ...
    async def eliminar_async(self, tid: int) -> bool: ...
    async def existe_referenciado_async(self, tid: int, nombre_original: str) -> bool: ...
