from __future__ import annotations

from typing import Protocol

from src.domain.entities.afp_entity import AfpEntity
from src.domain.entities.arl_entity import ArlEntity
from src.domain.entities.banco_entity import BancoEntity
from src.domain.entities.canal_entity import CanalEntity
from src.domain.entities.ejecutivo_catalogo_entity import EjecutivoCatalogoEntity
from src.domain.entities.eps_entity import EpsEntity
from src.domain.entities.oficina_entity import OficinaEntity
from src.domain.entities.profesion_entity import ProfesionEntity


class ReferenciaRepository(Protocol):
    async def listar_ejecutivos_async(self) -> list[EjecutivoCatalogoEntity]: ...
    async def obtener_ejecutivo_async(self, usuario_asesor: str) -> EjecutivoCatalogoEntity | None: ...
    async def guardar_ejecutivo_async(self, entity: EjecutivoCatalogoEntity) -> EjecutivoCatalogoEntity: ...
    async def listar_canales_async(self) -> list[CanalEntity]: ...
    async def listar_canales_por_ciudad_async(self, cid: int) -> list[CanalEntity]: ...
    async def listar_canales_filtrados_async(self, cpid: int | None, cspid: int | None) -> list[CanalEntity]: ...
    async def listar_oficinas_async(self) -> list[OficinaEntity]: ...
    async def listar_oficinas_filtradas_async(self, cid: int | None, cod_canales: int | None, cspid: int | None = None) -> list[OficinaEntity]: ...
    async def listar_profesiones_async(self) -> list[ProfesionEntity]: ...
    async def listar_eps_async(self) -> list[EpsEntity]: ...
    async def listar_afp_async(self) -> list[AfpEntity]: ...
    async def listar_arl_async(self) -> list[ArlEntity]: ...
    async def listar_bancos_async(self) -> list[BancoEntity]: ...
