from __future__ import annotations

from typing import Protocol

from src.domain.entities.usuario_entity import UsuarioEntity
from src.domain.value_objects.estado_usuario import EstadoUsuario


class UsuarioRepository(Protocol):
    async def obtener_por_nombre_async(self, nombre: str) -> UsuarioEntity | None: ...
    async def obtener_por_uid_async(self, uid: int) -> UsuarioEntity | None: ...
    async def actualizar_password_async(self, uid: int, nuevo_hash: str) -> None: ...
    # --- AP-0001: gestión de estado de cuenta ---
    async def listar_paginado_async(
        self, page: int, page_size: int, texto: str | None, activo: bool | None
    ) -> tuple[list[UsuarioEntity], int]: ...
    async def obtener_cualquiera_por_uid_async(self, uid: int) -> UsuarioEntity | None: ...
    async def actualizar_estado_async(self, uid: int, activo: bool) -> None: ...
    async def obtener_uid_por_documento_async(self, numero_documento: str) -> int | None: ...
    # --- AP-0133 y AP-0049: verificacion viva del estado de la cuenta por peticion ---
    async def resolver_estado(self, uid: int) -> EstadoUsuario: ...
